server:
  port: 4444

#spring:
 # cloud:
  #  config:
   #   server:
    #    git:
     #     uri: https://github.com/AmaruAtreides/confiles
      #    username:
       #   password:
        #  force-pull: true
         # skipSslValidation: true
