zuul:
  routes:
    microusuario:
      path: /usuarios/**
      service-id: microusuario
   #   sensitiveHeaders: Cookie,Set-Cookie,Authorization
    micropeticion:
      path: /peticiones/**
      service-id: micropeticion
  #    sensitiveHeaders: Cookie,Set-Cookie,Authorization
    securityserverdemo:
      path: /api/security/**
      sensitive-headers:
      service-id: securityserverdemo
   #   sensitiveHeaders: Cookie,Set-Cookie,Authorization
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 6565
