# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
      status-page-url-path: /infoHystrix
      health-check-url-path: /healthHystrix
      metadata-map:
        app-owner: Maru
        description: cliente hystrix P1


