#HTTP Server
server:
  port: 8888

#Discovery Server Access
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: /infoRibbon
    health-check-url-path: /healthRibbon
    metadata-map:
      app-owner: Maru
      description: primer preba de cliente eureka
